### ISSUE TITLE
experiment_meta_learning.py errors

### ISSUE THREAD

**Issue by iacopo97** [deepmind/functa#4]
Hi, 
while I am running experiment_meta_learning.py, I obtain the following error:

absl.flags._exceptions.UnparsedFlagAccessError: Trying to access flag --config before flags were parsed.
During handling of the above exception, another exception occurred:
absl.flags._exceptions.UnparsedFlagAccessError: Trying to access flag --jaxline_post_mortem before flags were parsed.

If I run test_celeb_a_hq.py/test_srn_cars.py the code works smoothly

**Comment by iacopo97** [comment]
I have found a solution that works for me. the following part is needed at the end of the code instead of platform.main.
if name == 'main':
flags.mark_flag_as_required('config')
app.run(functools.partial(platform.main, Experiment))
Then I included the following python modules:
from absl import app
import functools

At the end I introduce inside the function get config():
´´´
config.checkpoint_dir = '/tmp/training/' #this is my checkpoint_directory, I have specified this directory also for config.eval_specific_checkpoint_dir

Then in order to execute the experiment_meta_learning.py i use the following line in the terminal:
python3 ./experiment_meta_learning.py --config ./experiment_meta_learning.py

**Comment by hyunjik11** [comment]
Hi, thank you for identifying this. I've updated the repo to incorporate your solution.
