### ISSUE TITLE
modulations of SRN_cars

### ISSUE THREAD

**Issue by iacopo97** [deepmind/functa#7]
How can I produce the modulations related to SRN_cars dataset?

**Comment by hyunjik11** [comment]
Hi, you'd need to modify `modulation_dataset_writer.py` to be compatible with scenes. You'd go about this by using setting `is_nerf=True` for the argument to `helpers.inner_loop` that's called in `modulation_dataset_writer.create_modulation_dataset`, and also make sure you replace the `coords` and `targets` arguments to `helpers.inner_loop` with the correct arrays, as is done in `experiment_meta_learning.py` for scenes. I hope this provides enough guidance to get you started, and let me know if you get stuck.

**Comment by iacopo97** [comment]
Yes, thank you very much. I have managed to do that
