### ISSUE TITLE
value of  model.l2_weight and value of noise_std

### ISSUE THREAD

**Issue by iacopo97** [deepmind/functa#8]
I would like to know if the value of **model.l2_weight** and **model.noise_std** for the training of both Celeba and SRN cars should be kept at 0 in order to achieve the best performance from the model. I have tried to find in the paper these values but I couldn't.

**Comment by hyunjik11** [comment]
Yes, these are hyperparameters that we experimented with but both should be set to zero.

**Comment by iacopo97** [comment]
Thanks a lot
